import { relations, sql } from "drizzle-orm";
import {
  bigint, boolean, check, customType, foreignKey, index, integer, jsonb, pgSchema,
  primaryKey, text, timestamp, unique, uniqueIndex, uuid,
} from "drizzle-orm/pg-core";
import type { ExecutionTarget, InvocationRequest, InvocationSource, TriggerKind } from "../job-domain";
import type { ArtifactKind, ArtifactState } from "../artifacts";

export const app = pgSchema("app");
const bytea = customType<{ data: Buffer }>({ dataType: () => "bytea" });
const tsvector = customType<{ data: string }>({ dataType: () => "tsvector" });
const createdAt = () => timestamp("created_at", { withTimezone: true, mode: "date" }).notNull().defaultNow();
const updatedAt = () => timestamp("updated_at", { withTimezone: true, mode: "date" }).notNull().defaultNow();

export const schemaMigrations = app.table("schema_migrations", {
  version: text("version").primaryKey(), appliedAt: timestamp("applied_at", { withTimezone: true }).notNull().defaultNow(),
});

export const tenants = app.table("tenants", { id: uuid("id").primaryKey(), name: text("name"), createdAt: createdAt(), updatedAt: updatedAt() });
export const authUsers = app.table("auth_users", { id: uuid("id").primaryKey(), email: text("email").notNull().unique(), emailVerified: boolean("email_verified").notNull().default(false), createdAt: createdAt() });
export const authAccounts = app.table("auth_accounts", {
  id: uuid("id").primaryKey(), userId: uuid("user_id").notNull().references(() => authUsers.id, { onDelete: "cascade" }), provider: text("provider").notNull(), providerAccountId: text("provider_account_id").notNull(), passwordHash: text("password_hash"),
}, t => [unique().on(t.provider, t.providerAccountId)]);
export const authResetTokens = app.table("auth_reset_tokens", { digest: text("digest").primaryKey(), userId: uuid("user_id").notNull().references(() => authUsers.id, { onDelete: "cascade" }), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), usedAt: timestamp("used_at", { withTimezone: true }) });
export const authSessions = app.table("auth_sessions", { id: uuid("id").primaryKey(), userId: uuid("user_id").notNull().references(() => authUsers.id, { onDelete: "cascade" }), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), revokedAt: timestamp("revoked_at", { withTimezone: true }) });
export const oauthDeviceAuthorizations = app.table("oauth_device_authorizations", {
  deviceCode: text("device_code").primaryKey(), userCode: text("user_code").notNull().unique(), record: jsonb("record").$type<Record<string, unknown>>().notNull(), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), createdAt: createdAt(), updatedAt: updatedAt(),
}, t => [index("oauth_device_authorizations_expires").on(t.expiresAt)]);
export const members = app.table("members", {
  tenantId: uuid("tenant_id").notNull().references(() => tenants.id, { onDelete: "cascade" }), userId: uuid("user_id").notNull().references(() => authUsers.id, { onDelete: "cascade" }), email: text("email").notNull(), role: text("role").$type<"owner" | "member">().notNull(), sessionVersion: integer("session_version").notNull().default(1), createdAt: createdAt(),
}, t => [primaryKey({ columns: [t.tenantId, t.userId] }), check("members_role_check", sql`${t.role} in ('owner','member')`), check("members_session_version_check", sql`${t.sessionVersion} > 0`)]);
export const accessTokens = app.table("access_tokens", {
  tenantId: uuid("tenant_id").notNull().references(() => tenants.id, { onDelete: "cascade" }), id: uuid("id").notNull(), name: text("name").notNull(), digest: text("digest").notNull().unique(), userId: uuid("user_id").notNull(), sessionVersion: integer("session_version").notNull(), scopes: jsonb("scopes").$type<string[]>().notNull().default([]), createdAt: createdAt(), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), lastUsedAt: timestamp("last_used_at", { withTimezone: true }), revokedAt: timestamp("revoked_at", { withTimezone: true }),
}, t => [primaryKey({ columns: [t.tenantId, t.id] }), foreignKey({ columns: [t.tenantId, t.userId], foreignColumns: [members.tenantId, members.userId] }).onDelete("cascade")]);

export const connections = app.table("connections", { tenantId: uuid("tenant_id").notNull().references(() => tenants.id, { onDelete: "cascade" }), kind: text("kind").notNull(), encryptedValue: text("encrypted_value").notNull(), updatedAt: updatedAt() }, t => [primaryKey({ columns: [t.tenantId, t.kind] })]);
export const githubInstallations = app.table("github_installations", { installationId: bigint("installation_id", { mode: "number" }).primaryKey(), tenantId: uuid("tenant_id").notNull().references(() => tenants.id, { onDelete: "cascade" }), accountLogin: text("account_login").notNull(), accountType: text("account_type").notNull(), state: text("state").$type<"active" | "suspended">().notNull(), updatedAt: updatedAt() }, t => [unique().on(t.tenantId, t.installationId), check("github_installations_state_check", sql`${t.state} in ('active','suspended')`)]);
export const githubSetupStates = app.table("github_setup_states", { tenantId: uuid("tenant_id").notNull().references(() => tenants.id, { onDelete: "cascade" }), nonce: text("nonce").notNull(), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), usedAt: timestamp("used_at", { withTimezone: true }) }, t => [primaryKey({ columns: [t.tenantId, t.nonce] })]);

export const jobs = app.table("jobs", {
  tenantId: uuid("tenant_id").notNull().references(() => tenants.id, { onDelete: "cascade" }), id: uuid("id").notNull(), name: text("name").notNull(), slug: text("slug").notNull(), encryptedPromptTemplate: text("encrypted_prompt_template").notNull(), encryptedRunNameTemplate: text("encrypted_run_name_template").notNull().default(""), executionTarget: jsonb("execution_target").$type<ExecutionTarget>().notNull(), model: text("model").notNull().default(""), effort: text("effort").notNull().default(""), concurrencyLimit: integer("concurrency_limit").notNull(), enabled: boolean("enabled").notNull().default(true), createdAt: createdAt(), updatedAt: updatedAt(),
}, t => [primaryKey({ columns: [t.tenantId, t.id] }), unique().on(t.tenantId, t.slug), check("jobs_concurrency_limit_check", sql`${t.concurrencyLimit} >= 1`)]);
export const triggers = app.table("triggers", {
  tenantId: uuid("tenant_id").notNull(), id: uuid("id").notNull(), jobId: uuid("job_id").notNull(), kind: text("kind").$type<TriggerKind>().notNull(), slug: text("slug").notNull(), enabled: boolean("enabled").notNull().default(true), config: jsonb("config").$type<Record<string, unknown>>().notNull().default({}), position: integer("position").notNull().default(0), createdAt: createdAt(), updatedAt: updatedAt(), removedAt: timestamp("removed_at", { withTimezone: true }),
}, t => [primaryKey({ columns: [t.tenantId, t.id] }), uniqueIndex("triggers_active_slug").on(t.tenantId, t.jobId, t.slug).where(sql`${t.removedAt} is null`), foreignKey({ columns: [t.tenantId, t.jobId], foreignColumns: [jobs.tenantId, jobs.id] }).onDelete("cascade"), check("triggers_kind_check", sql`${t.kind} in ('manual','schedule','webhook','jobLifecycle')`)]);
export const invocations = app.table("invocations", {
  tenantId: uuid("tenant_id").notNull(), id: uuid("id").notNull(), jobId: uuid("job_id").notNull(), source: text("source").$type<InvocationSource>().notNull(), claimKey: text("claim_key").notNull(), triggerId: uuid("trigger_id").notNull(), context: jsonb("context").$type<Record<string, unknown>>().notNull(), occurrence: jsonb("occurrence").$type<InvocationRequest["occurrence"]>(), createdAt: createdAt(),
}, t => [primaryKey({ columns: [t.tenantId, t.id] }), unique().on(t.tenantId, t.jobId, t.claimKey), foreignKey({ columns: [t.tenantId, t.jobId], foreignColumns: [jobs.tenantId, jobs.id] }).onDelete("cascade"), foreignKey({ columns: [t.tenantId, t.triggerId], foreignColumns: [triggers.tenantId, triggers.id] }), check("invocations_source_check", sql`${t.source} in ('manual','schedule','webhook','jobLifecycle')`)]);
export const jobRuns = app.table("job_runs", {
  tenantId: uuid("tenant_id").notNull(), id: uuid("id").notNull(), jobId: uuid("job_id").notNull(), invocationId: uuid("invocation_id").notNull(), state: text("state").notNull(), encryptedPrompt: text("encrypted_prompt").notNull(), runName: text("run_name").notNull().default(""), launchLeaseExpiresAt: timestamp("launch_lease_expires_at", { withTimezone: true }), nextPollAt: timestamp("next_poll_at", { withTimezone: true }), createdAt: createdAt(), updatedAt: updatedAt(), startedAt: timestamp("started_at", { withTimezone: true }),
}, t => [primaryKey({ columns: [t.tenantId, t.id] }), unique().on(t.tenantId, t.invocationId), foreignKey({ columns: [t.tenantId, t.jobId], foreignColumns: [jobs.tenantId, jobs.id] }).onDelete("cascade"), foreignKey({ columns: [t.tenantId, t.invocationId], foreignColumns: [invocations.tenantId, invocations.id] }).onDelete("cascade"), index("job_runs_queue").on(t.state, t.createdAt).where(sql`${t.state}='queued'`), index("job_runs_poll_due").on(t.nextPollAt).where(sql`${t.state} in ('running','blocked','stopping')`), index("job_runs_launch_lease").on(t.launchLeaseExpiresAt).where(sql`${t.state}='starting'`)]);

export const runs = app.table("runs", {
  tenantId: uuid("tenant_id").notNull(), id: uuid("id").notNull(), jobId: uuid("job_id").notNull(), invocationId: uuid("invocation_id").notNull(), provider: text("provider").notNull(), issueId: text("issue_id").notNull(), issueUrl: text("issue_url"), issueTitle: text("issue_title").notNull().default(""), runName: text("run_name").notNull().default(""), agentName: text("agent_name").notNull(), workspaceName: text("workspace_name").notNull().default(""), agentKind: text("agent_kind").notNull().default(""), state: text("state").notNull(), executionBackendKind: text("execution_backend_kind").notNull().default(""), executionHandle: jsonb("execution_handle").$type<Record<string, unknown>>(), executionCapabilities: jsonb("execution_capabilities").$type<string[]>().notNull().default([]), destinationUrl: text("destination_url"), artifactState: text("artifact_state").$type<ArtifactState>().notNull().default("pending"), artifactError: text("artifact_error"), claimReleased: boolean("claim_released").notNull().default(false), vmCleanupAttempt: integer("vm_cleanup_attempt").notNull().default(0), cleanupNextAt: timestamp("cleanup_next_at", { withTimezone: true }), vmCleanupComplete: boolean("vm_cleanup_complete").notNull().default(false), createdAt: createdAt(), updatedAt: updatedAt(),
}, t => [primaryKey({ columns: [t.tenantId, t.id] }), unique().on(t.tenantId, t.invocationId), foreignKey({ columns: [t.tenantId, t.jobId], foreignColumns: [jobs.tenantId, jobs.id] }).onDelete("cascade"), foreignKey({ columns: [t.tenantId, t.invocationId], foreignColumns: [invocations.tenantId, invocations.id] }).onDelete("cascade"), index("runs_order").on(t.tenantId, t.createdAt.desc(), t.id.desc()), index("runs_state_order").on(t.tenantId, t.state, t.createdAt.desc(), t.id.desc()), index("runs_cleanup_due").on(t.cleanupNextAt).where(sql`not ${t.vmCleanupComplete}`), index("runs_issue_trgm").using("gin", sql`${t.issueId} gin_trgm_ops`), index("runs_name_trgm").using("gin", sql`${t.runName} gin_trgm_ops`)]);
export const runArtifacts = app.table("run_artifacts", {
  tenantId: uuid("tenant_id").notNull(), runId: uuid("run_id").notNull(), id: uuid("id").notNull(), kind: text("kind").$type<ArtifactKind>().notNull(), objectKey: text("object_key").notNull(), provider: text("provider").notNull(), format: text("format").notNull(), formatVersion: text("format_version"), cliVersion: text("cli_version"), nativeSessionId: text("native_session_id"), byteSize: bigint("byte_size", { mode: "number" }).notNull(), sha256: text("sha256").notNull(), state: text("state").$type<ArtifactState>().notNull(), createdAt: createdAt(),
}, t => [primaryKey({ columns: [t.tenantId, t.id] }), unique().on(t.tenantId, t.objectKey), foreignKey({ columns: [t.tenantId, t.runId], foreignColumns: [runs.tenantId, runs.id] }).onDelete("cascade"), index("run_artifacts_by_run").on(t.tenantId, t.runId, t.createdAt, t.id)]);
export const runTraceEvents = app.table("run_trace_events", {
  tenantId: uuid("tenant_id").notNull(), runId: uuid("run_id").notNull(), sequence: bigint("sequence", { mode: "number" }).notNull(), id: text("id").notNull(), parentId: text("parent_id"), eventType: text("event_type").notNull(), role: text("role"), title: text("title").notNull(), previewText: text("preview_text").notNull(), displayData: jsonb("display_data").$type<Record<string, unknown>>().notNull().default({}), occurredAt: timestamp("occurred_at", { withTimezone: true }), createdAt: createdAt(), searchVector: tsvector("search_vector").generatedAlwaysAs(sql`to_tsvector('english', title || ' ' || preview_text)`),
}, t => [primaryKey({ columns: [t.tenantId, t.runId, t.sequence] }), foreignKey({ columns: [t.tenantId, t.runId], foreignColumns: [runs.tenantId, runs.id] }).onDelete("cascade"), index("run_trace_events_search").using("gin", t.searchVector), index("run_trace_events_by_type").on(t.tenantId, t.runId, t.eventType, t.sequence)]);
export const runActivity = app.table("run_activity", { tenantId: uuid("tenant_id").notNull(), id: uuid("id").notNull(), runId: uuid("run_id").notNull(), action: text("action").notNull(), detail: text("detail").notNull(), createdAt: createdAt() }, t => [primaryKey({ columns: [t.tenantId, t.id] }), foreignKey({ columns: [t.tenantId, t.runId], foreignColumns: [runs.tenantId, runs.id] }).onDelete("cascade")]);
export const activeClaims = app.table("active_claims", { tenantId: uuid("tenant_id").notNull(), jobId: uuid("job_id").notNull(), claimKey: text("claim_key").notNull(), runId: uuid("run_id").notNull(), expiresAt: timestamp("expires_at", { withTimezone: true }) }, t => [primaryKey({ columns: [t.tenantId, t.jobId, t.claimKey] }), foreignKey({ columns: [t.tenantId, t.jobId], foreignColumns: [jobs.tenantId, jobs.id] }).onDelete("cascade"), foreignKey({ columns: [t.tenantId, t.runId], foreignColumns: [runs.tenantId, runs.id] }).onDelete("cascade")]);

export const scheduleState = app.table("schedule_state", { tenantId: uuid("tenant_id").notNull(), triggerId: uuid("trigger_id").notNull(), jobId: uuid("job_id").notNull(), nextRunAt: timestamp("next_run_at", { withTimezone: true }), lastTriggeredAt: timestamp("last_triggered_at", { withTimezone: true }) }, t => [primaryKey({ columns: [t.tenantId, t.triggerId] }), foreignKey({ columns: [t.tenantId, t.triggerId], foreignColumns: [triggers.tenantId, triggers.id] }).onDelete("cascade"), foreignKey({ columns: [t.tenantId, t.jobId], foreignColumns: [jobs.tenantId, jobs.id] }).onDelete("cascade"), index("schedules_due").on(t.nextRunAt).where(sql`${t.nextRunAt} is not null`)]);
export const automaticWakes = app.table("automatic_wakes", { tenantId: uuid("tenant_id").notNull(), jobId: uuid("job_id").notNull(), trailingPending: boolean("trailing_pending").notNull().default(false), summary: jsonb("summary").$type<Record<string, unknown>>().notNull().default({}), updatedAt: updatedAt() }, t => [primaryKey({ columns: [t.tenantId, t.jobId] }), foreignKey({ columns: [t.tenantId, t.jobId], foreignColumns: [jobs.tenantId, jobs.id] }).onDelete("cascade")]);
export const lifecycleDeliveries = app.table("lifecycle_deliveries", { tenantId: uuid("tenant_id").notNull(), triggerId: uuid("trigger_id").notNull(), sourceRunId: uuid("source_run_id").notNull(), terminalState: text("terminal_state").notNull(), createdAt: createdAt() }, t => [primaryKey({ columns: [t.tenantId, t.triggerId, t.sourceRunId, t.terminalState] }), foreignKey({ columns: [t.tenantId, t.triggerId], foreignColumns: [triggers.tenantId, triggers.id] }).onDelete("cascade"), foreignKey({ columns: [t.tenantId, t.sourceRunId], foreignColumns: [runs.tenantId, runs.id] }).onDelete("cascade")]);
export const jobEvents = app.table("job_events", { tenantId: uuid("tenant_id").notNull(), id: uuid("id").notNull(), jobId: uuid("job_id").notNull(), provider: text("provider").notNull(), deliveryId: text("delivery_id").notNull(), outcome: text("outcome").notNull(), detail: text("detail").notNull(), receivedAt: timestamp("received_at", { withTimezone: true }).notNull().defaultNow() }, t => [primaryKey({ columns: [t.tenantId, t.id] }), foreignKey({ columns: [t.tenantId, t.jobId], foreignColumns: [jobs.tenantId, jobs.id] }).onDelete("cascade"), index("job_events_by_job").on(t.tenantId, t.jobId, t.receivedAt)]);
export const webhookDeliveries = app.table("webhook_deliveries", { tenantId: uuid("tenant_id").notNull().references(() => tenants.id, { onDelete: "cascade" }), id: uuid("id").notNull(), provider: text("provider").notNull(), deliveryId: text("delivery_id").notNull(), eventType: text("event_type").notNull().default("unknown"), eventAction: text("event_action").notNull().default("unknown"), outcome: text("outcome").notNull(), detail: text("detail").notNull(), receivedAt: timestamp("received_at", { withTimezone: true }).notNull().defaultNow() }, t => [primaryKey({ columns: [t.tenantId, t.id] }), unique().on(t.tenantId, t.provider, t.deliveryId)]);
export const webhookDeliveryEvents = app.table("webhook_delivery_events", { tenantId: uuid("tenant_id").notNull(), id: uuid("id").notNull(), deliveryId: uuid("delivery_id").notNull(), jobId: uuid("job_id"), outcome: text("outcome").notNull(), detail: text("detail").notNull(), createdAt: createdAt() }, t => [primaryKey({ columns: [t.tenantId, t.id] }), foreignKey({ columns: [t.tenantId, t.deliveryId], foreignColumns: [webhookDeliveries.tenantId, webhookDeliveries.id] }).onDelete("cascade"), foreignKey({ columns: [t.tenantId, t.jobId], foreignColumns: [jobs.tenantId, jobs.id] }).onDelete("cascade")]);
export const pendingVerifications = app.table("pending_verifications", { tenantId: uuid("tenant_id").notNull().references(() => tenants.id, { onDelete: "cascade" }), id: uuid("id").notNull(), jobId: uuid("job_id").notNull(), triggerId: uuid("trigger_id").notNull(), deliveryId: text("delivery_id").notNull(), installationId: bigint("installation_id", { mode: "number" }).notNull(), repositoryId: bigint("repository_id", { mode: "number" }).notNull(), repositoryOwner: text("repository_owner").notNull(), repositoryName: text("repository_name").notNull(), pullNumber: integer("pull_number").notNull(), attempt: integer("attempt").notNull().default(0), nextAttemptAt: timestamp("next_attempt_at", { withTimezone: true }).notNull(), payload: jsonb("payload").$type<Record<string, unknown>>().notNull() }, t => [primaryKey({ columns: [t.tenantId, t.id] }), foreignKey({ columns: [t.tenantId, t.jobId], foreignColumns: [jobs.tenantId, jobs.id] }).onDelete("cascade"), foreignKey({ columns: [t.tenantId, t.triggerId], foreignColumns: [triggers.tenantId, triggers.id] }).onDelete("cascade"), index("pending_verifications_due").on(t.nextAttemptAt)]);
export const tailFingerprints = app.table("tail_fingerprints", { tenantId: uuid("tenant_id").notNull().references(() => tenants.id, { onDelete: "cascade" }), jobId: uuid("job_id").notNull(), fingerprint: text("fingerprint").notNull(), windowStartedAt: timestamp("window_started_at", { withTimezone: true }).notNull(), count: integer("count").notNull() }, t => [primaryKey({ columns: [t.tenantId, t.jobId, t.fingerprint] }), foreignKey({ columns: [t.tenantId, t.jobId], foreignColumns: [jobs.tenantId, jobs.id] }).onDelete("cascade")]);
export const wakeHints = app.table("wake_hints", { key: text("key").primaryKey().default("global"), notBefore: timestamp("not_before", { withTimezone: true }).notNull(), updatedAt: updatedAt() });
export const runTraceCursors = app.table("run_trace_cursors", { tenantId: uuid("tenant_id").notNull(), runId: uuid("run_id").notNull(), generation: text("generation").notNull(), committedOffset: bigint("committed_offset", { mode: "number" }).notNull().default(0), pendingBytes: bytea("pending_bytes").notNull().default(sql`''::bytea`), nextSequence: bigint("next_sequence", { mode: "number" }).notNull().default(1), rollingHash: text("rolling_hash").notNull().default("0".repeat(64)), updatedAt: updatedAt() }, t => [primaryKey({ columns: [t.tenantId, t.runId] }), foreignKey({ columns: [t.tenantId, t.runId], foreignColumns: [runs.tenantId, runs.id] }).onDelete("cascade")]);
export const runTraceChunks = app.table("run_trace_chunks", { tenantId: uuid("tenant_id").notNull(), runId: uuid("run_id").notNull(), generation: text("generation").notNull(), startOffset: bigint("start_offset", { mode: "number" }).notNull(), endOffset: bigint("end_offset", { mode: "number" }).notNull(), chunkSha256: text("chunk_sha256").notNull(), previousHash: text("previous_hash").notNull(), rollingHash: text("rolling_hash").notNull(), createdAt: createdAt() }, t => [primaryKey({ columns: [t.tenantId, t.runId, t.generation, t.startOffset] }), foreignKey({ columns: [t.tenantId, t.runId], foreignColumns: [runs.tenantId, runs.id] }).onDelete("cascade")]);

export const tenantRelations = relations(tenants, ({ many }) => ({ members: many(members), jobs: many(jobs), connections: many(connections) }));
export const jobRelations = relations(jobs, ({ one, many }) => ({
  tenant: one(tenants, { fields: [jobs.tenantId], references: [tenants.id] }),
  triggers: many(triggers), invocations: many(invocations), jobRuns: many(jobRuns), runs: many(runs),
}));
export const triggerRelations = relations(triggers, ({ one, many }) => ({
  job: one(jobs, { fields: [triggers.tenantId, triggers.jobId], references: [jobs.tenantId, jobs.id] }),
  invocations: many(invocations), schedule: one(scheduleState), lifecycleDeliveries: many(lifecycleDeliveries),
}));
export const invocationRelations = relations(invocations, ({ one }) => ({
  job: one(jobs, { fields: [invocations.tenantId, invocations.jobId], references: [jobs.tenantId, jobs.id] }),
  trigger: one(triggers, { fields: [invocations.tenantId, invocations.triggerId], references: [triggers.tenantId, triggers.id] }),
  jobRun: one(jobRuns), run: one(runs),
}));
export const runRelations = relations(runs, ({ one, many }) => ({
  job: one(jobs, { fields: [runs.tenantId, runs.jobId], references: [jobs.tenantId, jobs.id] }),
  invocation: one(invocations, { fields: [runs.tenantId, runs.invocationId], references: [invocations.tenantId, invocations.id] }),
  artifacts: many(runArtifacts), traceEvents: many(runTraceEvents), activity: many(runActivity),
}));

export const databaseSchema = {
  schemaMigrations, tenants, authUsers, authAccounts, authResetTokens, authSessions, oauthDeviceAuthorizations, members, accessTokens,
  connections, githubInstallations, githubSetupStates, jobs, triggers, invocations, jobRuns, runs, runArtifacts,
  runTraceEvents, runActivity, activeClaims, scheduleState, automaticWakes, lifecycleDeliveries, jobEvents,
  webhookDeliveries, webhookDeliveryEvents, pendingVerifications, tailFingerprints, wakeHints, runTraceCursors, runTraceChunks,
  tenantRelations, jobRelations, triggerRelations, invocationRelations, runRelations,
};
