import { readFileSync, writeFileSync } from "node:fs";
import { stringify } from "yaml";
import { generateOpenApi } from "../src/api-contract";

const target = new URL("../../docs/openapi.yaml", import.meta.url);
export const generated =
  "# Generated by npm run generate:openapi. Edit packages/api/src/api-contract.ts.\n" +
  stringify(generateOpenApi(), { lineWidth: 0, aliasDuplicateObjects: false });
if (process.argv.includes("--check")) {
  if (readFileSync(target, "utf8") !== generated) {
    console.error(
      "OpenAPI is stale. Run npm run generate:openapi and commit packages/docs/openapi.yaml.",
    );
    process.exitCode = 1;
  } else console.log("Generated OpenAPI is current.");
} else {
  writeFileSync(target, generated);
  console.log("Generated packages/docs/openapi.yaml.");
}
