import { before, after, test } from "node:test";
import assert from "node:assert/strict";
import { createServer } from "node:http";
import { readFile } from "node:fs/promises";
import { chromium } from "playwright";
let server, origin, browser;
const jobId = "00000000-0000-4000-8000-000000000001", runId = "00000000-0000-4000-8000-000000000002", time = "2026-10-09T12:00:00Z";
before(async () => { server = createServer(async (req, res) => { const path = new URL(req.url, "http://local").pathname, file = (/^(\/assets\/|\/theme-init.js$|\/bee-mark-monochrome.png$|\/favicon.ico$)/.test(path)) ? path : "/index.html"; try { const body = await readFile(new URL("../dist" + file, import.meta.url)); res.setHeader("Content-Type", file.endsWith(".js") ? "application/javascript" : file.endsWith(".css") ? "text/css" : "text/html"); res.end(body); } catch { res.statusCode = 404; res.end(); } }); await new Promise(resolve => server.listen(0, "127.0.0.1", resolve)); origin = "http://127.0.0.1:" + server.address().port; browser = await chromium.launch({ headless: true }); });
after(async () => { await browser?.close(); if (server) await new Promise(resolve => server.close(resolve)); });
async function setup() { const context = await browser.newContext(), page = await context.newPage(); page.setDefaultTimeout(10000); await page.route("**/api/v1/session", route => route.fulfill({ json: { authenticated: true, user: { id: "owner", email: "owner@example.test" }, workspace: { id: "tenant", name: "Workspace" }, capabilities: [], expiresAt: "2026-10-10T00:00:00Z" } })); return { context, page }; }
test("all-jobs runs index uses a tenant-scoped page, navigation, refresh, and created time", async () => {
  const { context, page } = await setup(); const requests = []; let refreshes = 0;
  const runs = Array.from({ length: 21 }, (_, index) => ({ id: `00000000-0000-4000-8000-${String(index + 1).padStart(12, "0")}`, run_name: `Run ${index}`, state: index === 0 ? "running" : "succeeded", created_at: time, updated_at: time, started_at: index === 0 ? time : null, agent_kind: "codex" }));
  await page.route("**/api/v1/runs?**", route => { const url = new URL(route.request().url()); requests.push(url); refreshes++; const second = url.searchParams.has("cursor"); return route.fulfill({ json: { items: second ? [runs[20]] : runs.slice(0, 20), nextCursor: second ? null : "page-2" } }); });
  await page.goto(origin + "/job-runs"); await page.getByRole("heading", { name: "Runs", exact: true }).waitFor(); await page.getByRole("link", { name: "Run 0", exact: true }).waitFor();
  assert.equal(await page.getByRole("link", { name: "Jobs", exact: true }).getAttribute("href"), "/jobs?q="); assert.equal(await page.getByRole("link", { name: "Runs", exact: true }).evaluate(el => el.className.includes("text-factorize-700")), true);
  assert.equal(await page.getByText("Run 0", { exact: true }).count(), 1); assert.equal(await page.locator("td time").count(), 20); assert.equal(await page.locator("td time").first().getAttribute("datetime"), time);
  assert.ok(requests.every(url => url.searchParams.get("limit") === "20" && !url.searchParams.has("jobId")));
  await page.getByRole("link", { name: "Next page" }).click(); await page.getByRole("link", { name: "Run 20", exact: true }).waitFor(); await page.reload(); await page.getByRole("link", { name: "Run 20", exact: true }).waitFor(); assert.ok(refreshes >= 2);
  await context.close();
});
test("shared run status dots show running transitions in both tables", async () => {
  const { context, page } = await setup(); let state = "running";
  await page.route(`**/api/v1/jobs/${jobId}`, route => route.fulfill({ json: { id: jobId, name: "Job", enabled: true, model: "", agentKind: "codex", concurrencyLimit: 1, runningCount: state === "running" ? 1 : 0, promptTemplate: "Prompt", triggers: [] } }));
  await page.route("**/api/v1/runs?**", route => route.fulfill({ json: { items: [{ id: runId, run_name: "Transition run", state, created_at: time, agent_kind: "codex" }], nextCursor: null } }));
  await page.goto(origin + "/job-runs");
  await page.getByRole("img", { name: "Status: Running" }).waitFor();
  assert.match(await page.getByRole("img", { name: "Status: Running" }).getAttribute("class"), /animate-pulse/);
  state = "succeeded"; await page.reload();
  await page.getByRole("img", { name: "Status: Succeeded" }).waitFor();
  assert.doesNotMatch(await page.getByRole("img", { name: "Status: Succeeded" }).getAttribute("class"), /animate-pulse/);
  state = "failed"; await page.goto(origin + `/jobs/${jobId}`);
  await page.getByRole("img", { name: "Status: Failed" }).waitFor();
  assert.doesNotMatch(await page.getByRole("img", { name: "Status: Failed" }).getAttribute("class"), /animate-pulse/);
  await context.close();
});
test("job run history restores its cursor on direct refresh and ignores legacy filters", async () => {
  const { context, page } = await setup(); const requests = [];
  await page.route(`**/api/v1/jobs/${jobId}`, route => route.fulfill({ json: { id: jobId, name: "Job", enabled: true, model: "", agentKind: "codex", concurrencyLimit: 1, runningCount: 0, promptTemplate: "Prompt", triggers: [] } }));
  await page.route("**/api/v1/runs?**", route => { const url = new URL(route.request().url()); requests.push(url); return route.fulfill({ json: { items: [{ id: runId, run_name: url.searchParams.has("cursor") ? "Second run" : "First run", state: "succeeded", created_at: time, agent_kind: "codex" }], nextCursor: url.searchParams.has("cursor") ? null : "next-cursor" } }); });
  await page.goto(origin + `/jobs/${jobId}?state=succeeded&contextQuery=needle`); await page.getByRole("link", { name: "First run", exact: true }).waitFor(); await page.getByRole("link", { name: "Next page" }).click(); await page.getByRole("link", { name: "Second run", exact: true }).waitFor(); await page.reload(); await page.getByRole("link", { name: "Second run", exact: true }).waitFor();
  assert.equal(new URL(page.url()).searchParams.get("cursor"), "next-cursor"); assert.ok(requests.every(url => url.searchParams.get("jobId") === jobId && url.searchParams.get("limit") === "30" && !url.searchParams.has("contextQuery") && !url.searchParams.has("state"))); await context.close();
});
test("prompt/provenance and diagnostics are lazy, terminal replay retries reuse a stable key and reset the visible trace", async () => {
  const { context, page } = await setup(); let revision = "old", detailReads = 0, diagnosticReads = 0; const replays = [];
  await page.route(`**/api/v1/runs/${runId}/status`, route => route.fulfill({ json: { id: runId, job_id: jobId, job_name: "Job", run_name: "Run", state: "succeeded", finalizing: false, trace_revision: revision, artifact_state: "stored", created_at: time, updated_at: time, started_at: time, destination_url: null } }));
  await page.route(`**/api/v1/runs/${runId}/trace-pages?**`, route => route.fulfill({ json: { items: [{ id: revision, sequence: 1, type: "assistant_message", title: revision === "old" ? "Old trace" : "Replayed trace", preview: "# Safe message\n[unsafe](javascript:alert(1))\n<script>alert(1)</script>", display: {} }], nextCursor: null, revision, reset: false } }));
  await page.route(`**/api/v1/runs/${runId}`, route => { detailReads++; return route.fulfill({ json: { prompt: "Private prompt", invocation: { source: "manual", context: { build: 42 }, trigger_id: "trigger-fixture", created_at: time, occurrence: { delivery: "fixture" } }, activity: [{ action: "started", detail: "Launched", created_at: time }] } }); });
  await page.route(`**/api/v1/runs/${runId}/diagnostics`, route => { diagnosticReads++; return route.fulfill({ json: { state: "succeeded", artifact: { state: "stored" }, harnessLog: { object_key: "retained/log.txt" }, execution: { detail: "Safe diagnostic" } } }); });
  await page.route(`**/api/v1/runs/${runId}/trace/replay`, route => { replays.push(route.request().postDataJSON()); if (replays.length === 1) return route.fulfill({ status: 503, json: { error: { code: "unavailable", message: "Retry replay" } } }); revision = "new"; return route.fulfill({ json: { status: "projected" } }); });
  await page.goto(origin + "/job-runs/" + runId); await page.getByText("Old trace · assistant_message", { exact: true }).click(); assert.equal(detailReads, 0); assert.equal(diagnosticReads, 0);
  assert.equal(await page.locator('a[href^="javascript:"]').count(), 0); assert.equal(await page.locator("main script").count(), 0);
  assert.equal(await page.getByRole("tab", { name: "Trace", exact: true }).getAttribute("aria-selected"), "true");
  const breadcrumbs = page.getByRole("navigation", { name: "Breadcrumb" });
  assert.equal(await breadcrumbs.getByRole("link", { name: "Jobs", exact: true }).getAttribute("href"), "/jobs?q=");
  assert.equal(await breadcrumbs.getByRole("link", { name: "Job", exact: true }).getAttribute("href"), "/jobs/" + jobId);
  await page.getByRole("tab", { name: "Info", exact: true }).click();
  await page.getByText("Created", { exact: true }).waitFor(); await page.getByText("Started", { exact: true }).waitFor(); await page.getByText("Queue time", { exact: true }).waitFor(); await page.getByText("Runtime", { exact: true }).waitFor(); await page.getByText("Execution destination", { exact: true }).waitFor();
  await page.getByText("Prompt, context and provenance", { exact: true }).click(); await page.getByText("Private prompt", { exact: true }).waitFor(); await page.getByText("trigger-fixture", { exact: true }).waitFor(); await page.getByRole("heading", { name: "Trigger context and occurrence" }).waitFor(); await page.getByText("Diagnostics and artifacts", { exact: true }).click(); await page.getByText(/retained\/log.txt/).waitFor(); assert.equal(detailReads, 1); assert.equal(diagnosticReads, 1);
  await page.getByRole("tab", { name: "Settings", exact: true }).click();
  await page.getByText("Replay trace", { exact: true }).click(); page.once("dialog", dialog => dialog.accept()); await page.getByRole("button", { name: "Replay retained trace" }).click(); await page.getByRole("alert").filter({ hasText: "Retry replay" }).waitFor(); await page.getByRole("tab", { name: "Trace", exact: true }).click(); await page.getByRole("tab", { name: "Settings", exact: true }).click(); await page.getByRole("alert").filter({ hasText: "Retry replay" }).waitFor(); page.once("dialog", dialog => dialog.accept()); await page.getByRole("button", { name: "Replay retained trace" }).click(); await page.getByRole("status").filter({ hasText: "projected" }).waitFor(); await page.getByRole("tab", { name: "Trace", exact: true }).click(); await page.getByText("Replayed trace · assistant_message", { exact: true }).waitFor();
  assert.equal(replays[0].requestId, replays[1].requestId); assert.equal(await page.getByText("Old trace · assistant_message", { exact: true }).count(), 0); await context.close();
});
test("stopping a run submits once, observes stopping state and keeps terminal finalization visible", async () => {
  const { context, page } = await setup(); let state = "running", stops = 0, releaseStop; const pendingStop = new Promise(resolve => { releaseStop = resolve; });
  await page.route(`**/api/v1/runs/${runId}/status`, route => route.fulfill({ json: { id: runId, job_id: jobId, job_name: "Job", run_name: "Run", state, finalizing: state === "stopped", trace_revision: "rev", artifact_state: "collecting", created_at: time, updated_at: time, started_at: time, destination_url: "https://example.test/run" } }));
  await page.route(`**/api/v1/runs/${runId}/trace-pages?**`, route => route.fulfill({ json: { items: [{ id: "command", sequence: 1, type: "command", title: "Build command", preview: '\x1b[31m<script>untrusted</script>\x1b[0m', display: {} }], nextCursor: null, revision: "rev", reset: false } }));
  await page.route(`**/api/v1/runs/${runId}/stop`, async route => { stops++; state = "stopping"; await pendingStop; return route.fulfill({ json: { state } }); });
  await page.goto(origin + "/job-runs/" + runId); await page.getByText("Build command · command", { exact: true }).click();
  const output = page.getByText("<script>untrusted</script>", { exact: true }); await output.waitFor(); assert.equal(await output.evaluate(node => getComputedStyle(node).color), "rgb(239, 68, 68)"); assert.equal(await page.locator("main script").count(), 0);
  await page.getByRole("button", { name: "Stop run", exact: true }).click(); await page.waitForFunction(() => Array.from(document.querySelectorAll("button")).some(button => button.textContent === "Stop run" && button.disabled)); releaseStop();
  await page.getByRole("status").filter({ hasText: /^stopping$/ }).waitFor(); assert.equal(stops, 1); state = "stopped";
  await page.getByText("stopped · Finalizing trace and artifacts", { exact: true }).waitFor(); assert.equal(await page.getByRole("button", { name: "Stop run", exact: true }).count(), 0);
  await context.close();
});
