import { z } from "zod";
import { tailIntegration } from "./editor-contracts";
const timestamp = z.string();
export const exeConnection = z.object({ connectionId: z.string(), agentKind: z.enum(["codex", "claude", "pi"]), tags: z.array(z.string()).default([]), models: z.array(z.string()).default([]), modelsRefreshedAt: timestamp.default("") });
export const ampConnection = z.object({ connectionId: z.string(), project: z.string(), apiBaseUrl: z.string().optional() });
export const integrationStatus = z.object({ linear: z.object({ organizationName: z.string().nullable(), viewerEmail: z.string().nullable() }).nullable(), clickup: z.object({ teamName: z.string().nullable() }).nullable(), exe: exeConnection.nullable(), exeConnections: z.array(exeConnection), ampConnections: z.array(ampConnection), cloudflareTail: z.object({ count: z.number().int(), installations: z.array(tailIntegration) }) });
export const authorizedClient = z.object({ grantId: z.string(), clientId: z.string(), clientName: z.string(), scopes: z.array(z.string()), authorizationDate: timestamp, expiresAt: timestamp.nullable(), lastUsedAt: timestamp.nullable() });
export const accessToken = z.object({ id: z.string(), name: z.string(), scopes: z.array(z.enum(["flows:read", "flows:write", "runs:read", "runs:write"])), created_at: timestamp, expires_at: timestamp, last_used_at: timestamp.nullable().optional(), revoked_at: timestamp.nullable().optional() });
export const createdAccessToken = accessToken.extend({ token: z.string() });
export const okResult = z.object({ ok: z.boolean() });
export const savedExe = okResult.extend({ connectionId: z.string(), models: z.array(z.string()) });
export const testedExe = okResult.extend({ missingPermissions: z.array(z.string()), tags: z.array(z.string()), checks: z.array(z.object({ command: z.string(), ok: z.boolean(), httpStatus: z.number(), exitCode: z.number().nullable(), output: z.string() })) });
export const savedAmp = okResult.extend({ connectionId: z.string() });
export const savedTail = z.object({ integrationId: z.string(), name: z.string(), status: z.literal("connected"), secretConfigured: z.literal(true), generatedSecret: z.string().optional() });
